server:
  port: 8887
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://118.25.97.210:3306/pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: Hwj@12345
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 18000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 118.25.97.210
    port: 6379
    timeout: 1000
  rabbitmq:
    port: 5672
    host: 118.25.97.210
    username: admin
    password: admin
  mail:
    host: smtp.qq.com
    port: 587
    username: 958098421@qq.com

    default-encoding: utf-8
    properties:
      mail:
        smtp-socketFactory-class: javax.net.ssl.SSLSocketFactor
        debug: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
